# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[project]
name = "mastodon-charm"
version = "0.0"
description = "Juju machine charm for the Mastodon federated social network server."
requires-python = ">=3.12"
dependencies = [
    "ops>=2.17,<4",
    "jinja2>=3.1",
    "cryptography>=43",
    "charmlibs-apt~=1.0",
    "charmlibs-passwd~=1.0",
    "charmlibs-systemd~=1.0",
    # For charms.grafana_agent.v0.cos_agent
    "cosl>=0.0.50",
    "pydantic>=2",
    # For charms.smtp_integrator.v0.smtp
    "email-validator>=2",
]

[dependency-groups]
dev = [
    "ops[testing]",
    "pytest",
    "coverage[toml]",
    "ruff",
]

[tool.pytest.ini_options]
minversion = "6.0"
log_cli_level = "INFO"
pythonpath = ["src", "lib"]

[tool.coverage.run]
branch = true
omit = ["lib/*", "tests/*"]

[tool.coverage.report]
show_missing = true

[tool.ruff]
line-length = 99
target-version = "py312"
extend-exclude = ["lib"]

[tool.ruff.lint]
select = ["E", "W", "F", "C", "N", "D", "I001", "UP", "B"]
ignore = [
    "D105",  # missing docstring in magic method
    "D107",  # missing docstring in __init__
    "E203",
]
per-file-ignores = { "tests/*" = ["D100", "D101", "D102", "D103", "D104"] }

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 15

[tool.pyright]
include = ["src"]
extraPaths = ["src", "lib"]
pythonVersion = "3.12"
typeCheckingMode = "standard"
reportMissingModuleSource = false
